podTemplate(
  containers: [
    containerTemplate(
        name: 'worker',
        image: 'harbor.maa-org.net/maa/jenkins-base:latest',
        ttyEnabled: true, 
        alwaysPullImage: true,
        command: 'cat',
        envVars: [
            containerEnvVar(key: 'THREAD', value: '2'),
            containerEnvVar(key: 'NUMBER_OF_RETRIES', value: '5'),
            containerEnvVar(key: 'MINIO_BUCKET', value: 'maa-release'),
            containerEnvVar(key: 'MINIO_ENDPOINT_DOMAIN', value: 'minio.local'),
            containerEnvVar(key: 'MINIO_ENDPOINT_PORT', value: '9080'),
            containerEnvVar(key: 'MINIO_WAIT_TIME_AFTER_UPLOAD_MS', value: '1000'),
            containerEnvVar(key: 'TZ', value: 'Asia/Shanghai'),
            containerEnvVar(key: 'OWNER', value: 'MaaAssistantArknights'),
            containerEnvVar(key: 'FILE_PATTERN', value: '-(?:win|linux)-|-macos-universal\\.dmg|-macos-runtime-universal\\.zip'),
            containerEnvVar(key: 'RELEASE_TAG', value: params.release_tag)
        ]
    )
  ]
) {
  node(POD_LABEL) {
    stage('Download files from GitHub Release and upload files to Minio') {
      withCredentials([
          string(credentialsId: 'maa-jenkins-robot-token', variable: 'GITHUB_PAT'),
          string(credentialsId: 'maa-minio-robot-access-key', variable: 'MINIO_ACCESS_KEY'),
          string(credentialsId: 'maa-minio-robot-secret-key', variable: 'MINIO_SECRET_KEY'),
          string(credentialsId: 'annangela-qqbot-token', variable: 'ANNANGELA_QQBOT_TOKEN')
      ]) {
          container('worker') {
            sh 'REPO=MaaAssistantArknights node /root/MaaRelease/scripts/s3-sync/index.js'
            sh 'REPO=MaaRelease node /root/MaaRelease/scripts/s3-sync/index.js'
          }
      }
      
    }
  }
}
