env:
  node: true
  es6: true
  es2020: true
  es2021: true
  es2022: true

parserOptions:
  ecmaVersion: latest
  sourceType: module

extends: eslint:recommended

ignorePatterns:
  - dist/

rules:
  logical-assignment-operators: error
  no-new-func: error
  no-new-object: error
  no-new-wrappers: error
  no-var: error
  prefer-const: error
  no-extra-parens: error
  no-misleading-character-class: error
  no-template-curly-in-string: error
  require-atomic-updates: error
  curly: error
  indent:
    - 2
    - 4
    - SwitchCase: 1
  linebreak-style:
    - 0
    - windows
  semi:
    - error
    - always
  no-console:
    - 0
  no-unused-vars:
    - 1
    - varsIgnorePattern: ^_
  no-redeclare:
    - 1
  no-unreachable:
    - 1
  no-inner-declarations:
    - 0
  comma-dangle:
    - 1
    - always-multiline
  eqeqeq: error
  dot-notation: error
  no-else-return: error
  no-extra-bind: error
  no-labels: error
  no-floating-decimal: error
  no-lone-blocks: error
  no-loop-func: error
  no-magic-numbers: off
  no-multi-spaces: error
  no-param-reassign: error
  strict:
    - error
    - global
  quotes:
    - 1
    - double
    - avoidEscape: true
  quote-props:
    - 1
    - as-needed
    - keywords: true
      unnecessary: true
      numbers: false
  no-empty:
    - error
    - allowEmptyCatch: true
  arrow-spacing:
    - error
    - before: true
      after: true
  prefer-arrow-callback: error
  prefer-spread: error
  prefer-template: error
  prefer-rest-params: error
  prefer-exponentiation-operator: error
  require-await: error
  arrow-parens: error
  no-use-before-define: error
