podTemplate(
  containers: [
    containerTemplate(
        name: 'worker',
        image: 'harbor.maa-org.net/maa/jenkins-base:latest',
        ttyEnabled: true,
        envVars: [
            containerEnvVar(key: 'MINIO_BUCKET', value: 'maa-release'),
            containerEnvVar(key: 'MINIO_ENDPOINT_DOMAIN', value: 'minio.local'),
            containerEnvVar(key: 'MINIO_ENDPOINT_PORT', value: '9080'),
            containerEnvVar(key: 'TZ', value: 'Asia/Shanghai'),
        ]
    )
  ]
) {
  node(POD_LABEL) {
    stage('Fetching the resources') {
      container('worker') {
        sh 'sh /root/MaaRelease/scripts/update_resource/updateResource.sh'
      }
    }
    stage('Uploading the resources') {
      withCredentials([
          string(credentialsId: 'maa-minio-robot-access-key', variable: 'MINIO_ACCESS_KEY'),
          string(credentialsId: 'maa-minio-robot-secret-key', variable: 'MINIO_SECRET_KEY'),
          string(credentialsId: 'annangela-qqbot-token', variable: 'ANNANGELA_QQBOT_TOKEN')
      ]) {
          container('worker') {
            sh '/root/mc alias set s3 http://$MINIO_ENDPOINT_DOMAIN:$MINIO_ENDPOINT_PORT $MINIO_ACCESS_KEY $MINIO_SECRET_KEY'
            sh '/root/mc mirror /root/MaaAssistantArknights/resource s3/maa-resources/MaaAssistantArknights/MaaAssistantArknights/resource --md5 --overwrite --preserve --remove'
          }
      }
    }
  }
}
