name: sync_release_to_ota2

on:
  workflow_dispatch:
    inputs:
      tag:
        required: false
        default: ""

jobs:
  sync_release_to_ota2:
    runs-on: ubuntu-latest
    steps:
        - id: latest-release
          if: ${{ inputs.tag == '' }}
          uses: pozetroninc/github-action-get-latest-release@master
          with:
            repository: 'MaaAssistantArknights/MaaRelease'
            excludes: "draft"
            token: ${{ secrets.GITHUB_TOKEN }}

        - uses: robinraju/release-downloader@v1
          with:
            repository: 'MaaAssistantArknights/MaaRelease'
            tag: ${{ inputs.tag || steps.latest-release.outputs.release }}
            fileName: '*'
            out-file-path: 'downloads'
            token: ${{ secrets.GITHUB_TOKEN }}

        - uses: robinraju/release-downloader@v1
          # 内测版本主仓库可能没有，没有就拉到
          continue-on-error: true
          with:
            repository: 'MaaAssistantArknights/MaaAssistantArknights'
            tag: ${{ inputs.tag || steps.latest-release.outputs.release }}
            fileName: '*'
            out-file-path: 'downloads'
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Upload to COS
          uses: zkqiang/tencent-cos-action@v0.1.0
          with:
            args: upload -rs downloads ${{ inputs.tag || steps.latest-release.outputs.release }}
            secret_id: ${{ secrets.MISTEO_MAARELEASE_COS_SECRET_ID }}
            secret_key: ${{ secrets.MISTEO_MAARELEASE_COS_SECRET_KEY }}
            bucket: ${{ secrets.MISTEO_MAARELEASE_COS_BUCKET }}
            region: ${{ secrets.MISTEO_MAARELEASE_COS_REG }}
