name: update-resource

on:
  push:
    paths:
      - .github/workflows/update_resource.yml
  workflow_dispatch:

jobs:
  sync-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Setup ssh key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.OTA_SERVER_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa -H ${{ secrets.OTA_SERVER_SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Update Resource
        run: |
          ssh ${{ secrets.OTA_SERVER_SSH_USER }}@${{ secrets.OTA_SERVER_SSH_HOST }} \
            "
              set -e
              mkdir -p ~/MaaAssistantArknights
              cd ~/MaaAssistantArknights
              git init
              git fetch --force --no-tags --prune --update-head-ok --progress  \
                'https://github.com/MaaAssistantArknights/MaaAssistantArknights' \
                '+HEAD:refs/remotes/origin/HEAD'
              git checkout --force --progress refs/remotes/origin/HEAD

              python ~/MaaRelease/scripts/update_resource/list.py \
                ~/MaaAssistantArknights/resource \
                ~/MaaAssistantArknights/resource/dynamic_list.txt

              mkdir ~/MaaRelease/MaaAssistantArknights/resource
              cp -r ./resource/* ~/MaaRelease/MaaAssistantArknights/resource
            "
